blank_issues_enabled: false
contact_links:
  - name: 🍿 420Grindhouse CyTube Channel
    url: https://cytu.be/r/420Grindhouse
    about: Join the community on the CyTube web stream.
  - name: 📺 SPUDZARENEAT's Grindhouse-TV
    url: https://github.com/spudzareneat/grindhouse-tv
    about: Web-based app inspiration by SPUDZARENEAT.
